import Blockly from 'node-blockly/browser';

export function loadPreset(presetNum, workspace) {
  workspace.clear()
  var xmlText = getPreset(presetNum)
  var xml = Blockly.Xml.textToDom(xmlText);
  Blockly.Xml.domToWorkspace(xml, workspace);
}

function getPreset(presetNum) {
  switch (presetNum) {
    case 1:
      return '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="reset" id="@/(C}pI$Qqk3xOnPB?c!" x="42" y="42"><next><block type="inc_experiment_num" id="GDu6Uw_dmdC$%0[-+35$"><field name="VAR">plantsNumber</field><next><block type="recordData" id="w{On#`xOv?Xm*C,U0gfS"><next><block type="wait" id=",m]=e:02!$L}G`[@2ot1"><field name="VAR">hour</field><next><block type="recordData" id="uV2vyK9T~]a0a?t%{tF9"><next><block type="wait" id="q7b,j6~2)rS1Qjt33g`L"><field name="VAR">hour</field><next><block type="recordData" id="/)+1uo?*3Nc*bzaX1x2/"><next><block type="wait" id="Sd:,F5;f^JaG^cK|X]K*"><field name="VAR">hour</field><next><block type="recordData" id="g;GV9fjsS(W_=N8sg|,x"><next><block type="wait" id="Sbe6[0n:[MuH%SDcda=6"><field name="VAR">hour</field><next><block type="recordData" id="[sMMs_A[C/K|ZDxX09n|"></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>'
    case 2:
      return '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="reset" id="@/(C}pI$Qqk3xOnPB?c!" x="39" y="49"><next><block type="inc_experiment_num" id="/(JOZM~{j2=F0q4G3aTL"><field name="VAR">plantsNumber</field><next><block type="controls_repeat_ext" id="pshQ9!1ly1bT7JuQQ;8O"><value name="TIMES"><block type="math_number" id="#B{t1LkJ~Z.e2fwz%~gh"><field name="NUM">30</field></block></value><statement name="DO"><block type="wait" id="_xH{hk)?{!DN@3kP8=Rq"><field name="VAR">minute</field><next><block type="wait" id="H@;9`V)%`.S-hi$UGIFb"><field name="VAR">minute</field><next><block type="recordData" id="[{eE*H;/AVj:6[bom=26"></block></next></block></next></block></statement></block></next></block></next></block></xml>'
    case 3:
      return '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="reset" id="@/(C}pI$Qqk3xOnPB?c!" x="39" y="49"><next><block type="inc_experiment_num" id="/(JOZM~{j2=F0q4G3aTL"><field name="VAR">plantsNumber</field><next><block type="controls_repeat_ext" id="pshQ9!1ly1bT7JuQQ;8O"><value name="TIMES"><block type="math_number" id="#B{t1LkJ~Z.e2fwz%~gh"><field name="NUM">30</field></block></value><statement name="DO"><block type="wait" id="_xH{hk)?{!DN@3kP8=Rq"><field name="VAR">minute</field><next><block type="wait" id="H@;9`V)%`.S-hi$UGIFb"><field name="VAR">minute</field><next><block type="recordData" id="[{eE*H;/AVj:6[bom=26"></block></next></block></next></block></statement><next><block type="reset" id="sJ`d/L4GKiZyiB(}*xN~"><next><block type="inc_experiment_num" id="3c#w}~6!QP/.VWc}KU)0"><field name="VAR">plantsNumber</field><next><block type="inc_experiment_num" id=":/KrsuR!NY/SgF{o]xxZ"><field name="VAR">snailsNumber</field><next><block type="controls_repeat_ext" id=":uHndDo?uA7_m:q[Ff]+"><value name="TIMES"><block type="math_number" id="caR`-eQeN|f,YC~N/88w"><field name="NUM">30</field></block></value><statement name="DO"><block type="wait" id="~)`9WJ!_-i@jN=^?YO(3"><field name="VAR">minute</field><next><block type="wait" id="DW(afVp}V/iP]u5A4yA_"><field name="VAR">minute</field><next><block type="recordData" id="Nk{d9t{A%#lLPD.-nRXh"></block></next></block></next></block></statement></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>'
    case 4:
      return '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="reset" id=";XQ{a~0`^LpFmcfO.VT|" x="32" y="45"><next><block type="inc_experiment_num" id="rUah:}V-I+`wa##jOF{n"><field name="VAR">plantsNumber</field><next><block type="controls_repeat_ext" id="uo%/H9{g:Zi65*9_ry{p"><value name="TIMES"><block type="math_number" id=";YQk1@JB.Y^uj=_SEMIB"><field name="NUM">10</field></block></value><statement name="DO"><block type="controls_repeat_ext" id="zNjQltD%[G68;dbnfYM;"><value name="TIMES"><block type="math_number" id="D[``^5b;:tL0b@Pv(;6q"><field name="NUM">5</field></block></value><statement name="DO"><block type="wait" id="6dEr]g3lvpj5am^C!,-P"><field name="VAR">minute</field><next><block type="recordData" id="7xY$Z4.SXJ-PIgua?P=Y"></block></next></block></statement><next><block type="controls_if" id="r7BI,a0e`5];)Q{.wZ=h"><mutation else="1"></mutation><value name="IF0"><block type="get_experiment_bool" id="P+6[]3%pz*1ky6$kRCz:"><field name="VAL">light</field><value name="BOOL"><block type="on_off_bool" id="Zj%(yWD{H@#[TFcV#/A]"><field name="BOOL">TRUE</field></block></value></block></value><statement name="DO0"><block type="set_experiment_bool" id="`!u/_p+G}[Jdwx:[u*oY"><field name="VAR">light</field><value name="VALUE"><block type="on_off_bool" id="WG+^s{a]A|]LpYIwbm(Y"><field name="BOOL">FALSE</field></block></value></block></statement><statement name="ELSE"><block type="set_experiment_bool" id="r_[0yd$mu]ITYw,^[Y=;"><field name="VAR">light</field><value name="VALUE"><block type="on_off_bool" id="#2D9ddCUffN-YX~R@c{z"><field name="BOOL">TRUE</field></block></value></block></statement></block></next></block></statement></block></next></block></next></block></xml>'
    case 5:
      return '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="reset" id=";XQ{a~0`^LpFmcfO.VT|" x="59" y="53"><next><block type="inc_experiment_num" id="R}Mme:mIUO*gLe6R5C]/"><field name="VAR">plantsNumber</field><next><block type="controls_repeat_ext" id="uo%/H9{g:Zi65*9_ry{p"><value name="TIMES"><block type="math_number" id=";YQk1@JB.Y^uj=_SEMIB"><field name="NUM">100</field></block></value><statement name="DO"><block type="wait" id="{WJ~/G|=WSy7v`DVe}Z*"><field name="VAR">minute</field><next><block type="controls_if" id="NX9+S`%{cQLO2/;Zg4#h"><value name="IF0"><block type="logic_compare" id="urVA]gzjYJ6R?~:7}E?R"><field name="OP">LT</field><value name="A"><block type="get_experiment_num" id="_M/8;Po|Zx5kL0F@_pb-"><field name="VAR">co2</field></block></value><value name="B"><block type="math_number" id=";x/;_%:yTO084[%]}C:F"><field name="NUM">380</field></block></value></block></value><statement name="DO0"><block type="set_experiment_bool" id="_JWR5,H08(m?xKkC(Pt|"><field name="VAR">light</field><value name="VALUE"><block type="on_off_bool" id="f!WS!:gl/!NY9rt#qMAM"><field name="BOOL">FALSE</field></block></value></block></statement><next><block type="controls_if" id="G`#52tv]qdEZaC0.tw0y"><value name="IF0"><block type="logic_compare" id="?hX.J#ZEb#Q,4)$d4RFm"><field name="OP">GT</field><value name="A"><block type="get_experiment_num" id="HA_k=d^$HEw/OR}}uQi]"><field name="VAR">co2</field></block></value><value name="B"><block type="math_number" id="xY^kZ[3?Si=,kZF(1s)Q"><field name="NUM">410</field></block></value></block></value><statement name="DO0"><block type="set_experiment_bool" id="Hh6d}WN14N6wvvlxFW4Y"><field name="VAR">light</field><value name="VALUE"><block type="on_off_bool" id="2Ou=Te^OcW-Z?!dD3@.9"><field name="BOOL">TRUE</field></block></value></block></statement><next><block type="recordData" id="7xY$Z4.SXJ-PIgua?P=Y"></block></next></block></next></block></next></block></statement></block></next></block></next></block></xml>'
  }
}